### ISSUE TITLE
Danvic.PSU登录界面密码问题

### ISSUE THREAD

**Issue by ywq216221** [danvic712/salary-insights#1]
@danvic712 博主，Danvic.PSU登录界面密码是什么啊？

**Comment by danvic712** [comment]
账户密码可以从 [Danvic.PSU/02_Infrastructure/PSU.EFCore/DbInitializer.cs](https://github.com/danvic712/Danvic.PSU/blob/master/Danvic.PSU/02_Infrastructure/PSU.EFCore/DbInitializer.cs) 文件中找到 

You can find the initial administrator account and password via the [Danvic.PSU/02_Infrastructure/PSU.EFCore/DbInitializer.cs](https://github.com/danvic712/Danvic.PSU/blob/master/Danvic.PSU/02_Infrastructure/PSU.EFCore/DbInitializer.cs) file

**Comment by ywq216221** [comment]
多谢哥哥












阿宝
***@***.***

淮阴工学院
学生
17851550337

---原始邮件---
发件人: "Danvic ***@***.***&gt;
发送时间: 2023年12月30日(周六) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [danvic712/salary-insights] Danvic.PSU登录界面密码问题 (Issue #1)




 
Closed #1 as completed.

**Comment by ywq216221** [comment]
博主，这个PSU.Site项目是ASP.NET Core Web 项目还是ASP.NET Core MVC Web 项目啊？还是ASP.NET Core MVC WebAPI项目啊？😭












阿宝
***@***.***

淮阴工学院
学生
17851550337

---原始邮件---
发件人: "Danvic ***@***.***&gt;
发送时间: 2023年12月30日(周六) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [danvic712/salary-insights] Danvic.PSU登录界面密码问题 (Issue #1)




 
Closed #1 as completed.

**Comment by danvic712** [comment]
是 ASP.NET Core MVC
