### ISSUE TITLE
前后端分离项目结构

### ISSUE THREAD

**Issue by ywq216221** [danvic712/salary-insights#2]
博主，我最近想写一个ASP.NET Core MVC WebAPI +Vue前后端分离项目，但是不知道项目结构应该分为哪些层？可以给我一些建议吗？这是我的邮箱账号abaoabao0417@qq.com

**Comment by danvic712** [comment]
你可以看看 [Common web application architectures](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures]) 这篇文章，对于后端常见的项目架构这里都做了一个介绍，如果你不是为了学习某种架构的话，按照最基础的来，落实职责分离的思想就可以了

对于 Vue,  前端的事交由前端去做，直接通过 Vite 创建出项目脚手架，后端提供 API 接口即可，微软也有提供一种混合架构，我当前的这个项目就是这种方式，详情可以查看 [Tutorial: Create an ASP.NET Core app with Vue in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)，传统的前后端分离的项目需要单独部署一个前端，一个后端站点，微软提供的这个脚手架是只需要部署一个站点，有好有坏，看你自己的选择

**Comment by ywq216221** [comment]
多谢啦












阿宝
***@***.***

淮阴工学院
学生
17851550337

---原始邮件---
发件人: "Danvic ***@***.***&gt;
发送时间: 2024年6月15日(周六) 上午8:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [danvic712/salary-insights] 前后端分离项目结构 (Issue #2)




 
你可以看看 Common web application architectures 这篇文章，对于后端常见的项目架构这里都做了一个介绍，如果你不是为了学习某种架构的话，按照最基础的来，落实职责分离的思想就可以了
 
对于 Vue,  前端的事交由前端去做，直接通过 Vite 创建出项目脚手架，后端提供 API 接口即可，微软也有提供一种混合架构，我当前的这个项目就是这种方式，详情可以查看 Tutorial: Create an ASP.NET Core app with Vue in Visual Studio，传统的前后端分离的项目需要单独部署一个前端，一个后端站点，微软提供的这个脚手架是只需要部署一个站点，有好有坏，看你自己的选择
